USE [Progra]
DBCC CHECKIDENT ('Corte', RESEED, 1)  
DBCC CHECKIDENT ('BitacoraCambio', RESEED, 1)  
DBCC CHECKIDENT ('ReciboPagado', RESEED, 1)  
DBCC CHECKIDENT ('Reconexion', RESEED, 1)  
DBCC CHECKIDENT ('Recibos', RESEED, 1)  
DBCC CHECKIDENT ('ComprobantePago', RESEED, 1)  
DBCC CHECKIDENT ('PropiedadDelPropietario', RESEED, 1)  
DBCC CHECKIDENT ('UsuarioDePropiedad', RESEED, 1)  
DBCC CHECKIDENT ('CCDePropiedad', RESEED, 1)  
DBCC CHECKIDENT ('Propietario', RESEED, 1)  
DBCC CHECKIDENT ('MovConsumo', RESEED, 1)  
DBCC CHECKIDENT ('Propiedad', RESEED, 1)  
--DBCC CHECKIDENT ('Usuario', RESEED, 1)  

